routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\PositionController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});
Route::get('/posisi', function () {
    return view('addPosition');
});
Route::resource('position',PositionController::class);
Route::resource('employee',EmployeeController::class);

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;
    protected $fillable = [
        'nama',
        'nip',
        'position_id',
        'departemen',
        'tanggal_lahir',
        'alamat',
        'nohp',
        'agama',
        'status',
        'foto'
    ];
}

app/Models/Position.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Position extends Model
{
    use HasFactory;
    protected $fillable = [
        'name'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Employee;
use App\Models\Position;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Employee::all();
        return view('employee',['data'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $model = new Employee;
        $data = Position::all();
        return view('addEmployee',[
            'model'=>$model,
            'position'=>$data
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        $model = new Employee;
        $data = Employee::where('nip', $request->nip)->get();
        if(count($data)==0){
            var_dump($data);
            //cek nip
            $model->nama = $request->nama;
            $model->nip = $request->nip;
            $model->position_id = $request->jabatan;
            $model->departemen = $request->departemen;
            $tanggal = $request->tgl." ".$request->tahun;
            $model->tanggal_lahir = $tanggal;
            $model->alamat = $request->alamat;
            $model->nohp = $request->nohp;
            $model->agama = $request->agama;
            $model->status = TRUE;
            $model->foto = $request->foto;
            $model->save();
            return redirect('employee');
            
        }else{
            // buat nambah pesan
            return redirect('employee');
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Employee::find($id);
        return view('detailEmployee',['data'=>$data]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Employee::find($id);
        $pos = Position::all();
        return view('editEmployee',[
            'data'=>$data,
            'position'=>$pos
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $model = Employee::find($id);
        if(isset($request->status)){
            if($request->status="aktif"){
                $model->status = TRUE;
            }else{
                $model->status = FALSE;
            }
        }else{
            $model->nama = $request->nama;
            $model->nip = $request->nip;
            $model->position_id = $request->jabatan;
            $model->departemen = $request->departemen;
            $tanggal=$request->tgl." ".$request->tahun;
            $model->tanggal_lahir = $tanggal;
            $model->alamat = $request->alamat;
            $model->nohp = $request->nohp;
            $model->agama = $request->agama;
            $model->foto = $request->foto;
        }
        $model->save();
        return redirect('employee');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $model = Employee::find($id);
        $model->delete();
        return redirect('employee');
    }
}

app/Http/Controllers/PositionController.php
<?php

namespace App\Http\Controllers;

use App\Models\Position;
use Illuminate\Http\Request;

class PositionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(request()->ajax()) {
            $positions = Position::all();
            return datatables($positions)
                ->addIndexColumn()
                ->toJson();
        }
        return view('position');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $model = new Position;
        $model->name = $request->posisi;
        $model->save();
        return view('addPosition');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function show(Position $position)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function edit(Position $position)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Position $position)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function destroy(Position $position)
    {
        //
    }
}

resources/views/addEmployee.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Pekerja</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
    </div>
    <div class="card-body">
      <form action="{{url('employee')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="nama">Nama</label>
          <input type="text" class="form-control" id="nama" name="nama" placeholder="Masukkan Nama">
        </div>
        <div class="form-group">
          <label for="NIP">NIP</label>
          <input type="text" class="form-control" id="NIP" name="nip"  placeholder="NIP">
        </div>
        <div class="form-group">
          <label for="Jabatan">Jabatan</label>
          <select class="form-control" id="Jabatan" name="jabatan">
            @foreach ($position as $p)
              <option value="{{$p->id}}">{{$p->name}}</option>
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="Departemen">Departemen</label>
          <input type="text" class="form-control" id="Departemen" name="departemen" placeholder="Departemen">
        </div>
        <div class="form-group">
          <label for="Tanggal_Lahir">Tanggal Lahir</label>
          <input type="text" class="form-control" id="Tanggal_Lahir" name="tgl" placeholder="Tanggal Lahir">
        </div>
        <div class="form-group">
          <label for="Tahun_Lahir">Tahun Lahir</label>
          <select class="form-control" id="Tahun_Lahir" name="tahun">
            @for ($i = 1990; $i < 2022; $i++)
              <option value="{{$i}}">{{$i}}</option>
            @endfor
          </select>
        </div>
        <div class="form-group">
          <label for="Alamat">Alamat</label>
          <textarea type="text" class="form-control" id="Alamat" name="alamat" placeholder="Alamat" rows="3"></textarea>
        </div>
        <div class="form-group">
          <label for="Nohp">Nomor Telepon</label>
          <input type="number" class="form-control" id="Nohp" name="nohp" placeholder="Nomor Telepon">
        </div>

        <div class="form-group">
          <label>Agama</label>
          <div class="custom-control custom-radio">
            <input type="radio" id="islam" name="agama" class="custom-control-input" value="islam">
            <label class="custom-control-label" for="islam">Islam</label>
          </div>
          <div class="custom-control custom-radio">
            <input type="radio" id="Kristen" name="agama" class="custom-control-input" value="kristen">
            <label class="custom-control-label" for="Kristen">Kristen</label>
          </div>
          <div class="custom-control custom-radio">
            <input type="radio" id="Budha" name="agama" class="custom-control-input" value="budha">
            <label class="custom-control-label" for="Budha">Budha</label>
          </div>
          <div class="custom-control custom-radio">
            <input type="radio" id="Hindu" name="agama" class="custom-control-input" value="hindu">
            <label class="custom-control-label" for="Hindu">Hindu</label>
          </div>
        </div>
        <div class="form-group">
          <label for="foto">File Foto KTP</label>
          <input type="file" class="form-control-file" id="foto" name="foto" placeholder="foto">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

      </form>
    </div>
</div>

@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="'js/huruf.js'"></script>
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('position.index') }}",
        columns: [
            { data: 'DT_RowIndex', orderable: false, searchable: false, className: "text-center"},
            { data: 'name' }
        ]
    })
</script>
@endpush

resources/views/addPosition.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Pekerja</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
    </div>
    <div class="card-body">
      <form action="{{url('position')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
          <label for="posisi">Posisi</label>
          <input type="text" class="form-control" id="posisi" name="posisi" placeholder="Masukkan Posisi">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

      </form>
    </div>
</div>

@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="'js/huruf.js'"></script>
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('position.index') }}",
        columns: [
            { data: 'DT_RowIndex', orderable: false, searchable: false, className: "text-center"},
            { data: 'name' }
        ]
    })
</script>
@endpush

resources/views/detailEmployee.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
    </ol>
</div>
@endsection
@section('content')

    <div class="container bootstrap snippets bootdey">
        <div class="panel-body inf-content">
            <div class="row">
                <div class="col-md-4">
                    <img alt="" style="width:600px;" title="" class="img-circle img-thumbnail isTooltip" src="https://bootdey.com/img/Content/avatar/avatar7.png" data-original-title="Usuario"> 
                </div>
                <div class="col-md-6">
                    <strong>Information</strong><br>
                    <div class="table-responsive">
                    <table class="table table-user-information">
                        <tbody>
                            <tr>        
                                <td>
                                    <strong>
                                        <span class="glyphicon glyphicon-asterisk text-primary"></span>
                                        nip                                                
                                    </strong>
                                </td>
                                <td class="text-primary">
                                    {{$data->nip}}     
                                </td>
                            </tr>
                            <tr>    
                                <td>
                                    <strong>
                                        <span class="glyphicon glyphicon-user  text-primary"></span>    
                                        Nama                                                
                                    </strong>
                                </td>
                                <td class="text-primary">
                                    {{$data->nama}}     
                                </td>
                            </tr>
                            <tr>        
                                <td>
                                    <strong>
                                        <span class="glyphicon glyphicon-cloud text-primary"></span>  
                                        Jabatan                                                
                                    </strong>
                                </td>
                                <td class="text-primary">
                                    {{$data->position_id}}     
                                </td>
                            </tr>
                            <tr>        
                                <td>
                                    <strong>
                                        <span class="glyphicon glyphicon-cloud text-primary"></span>  
                                        departemen                                                
                                    </strong>
                                </td>
                                <td class="text-primary">
                                    {{$data->departemen}}     
                                </td>
                            </tr>

                            <tr>        
                                <td>
                                    <strong>
                                        <span class="glyphicon glyphicon-bookmark text-primary"></span> 
                                        Tanggal Lahir                                                
                                    </strong>
                                </td>
                                <td class="text-primary">
                                    {{$data->tanggal_lahir}}     
                                </td>
                            </tr>
                            <tr>        
                                <td>
                                    <strong>
                                        <span class="glyphicon glyphicon-bookmark text-primary"></span> 
                                        Nomor Telepon                                               
                                    </strong>
                                </td>
                                <td class="text-primary">
                                    {{$data->nohp}}     
                                </td>
                            </tr>
                            <tr>        
                                <td>
                                    <strong>
                                        <span class="glyphicon glyphicon-bookmark text-primary"></span> 
                                        Agama                                              
                                    </strong>
                                </td>
                                <td class="text-primary">
                                    {{$data->agama}}     
                                </td>
                            </tr>
                            <tr>        
                                <td>
                                    <strong>
                                        <span class="glyphicon glyphicon-bookmark text-primary"></span> 
                                        Status                                               
                                    </strong>
                                </td>
                                <td class="text-primary">
                                    {{$data->status}}
                                </td>
                                <td>
                                    <form action="{{url('employee/'.$data->id)}}" method="post">
                                        @csrf
                                        <input type="hidden" name="_method" value="PATCH">
                                        @if($data->status=="aktif")
                                        <input type="hidden" name="status" value="tidak aktif">
                                        <input type="submit" class="btn btn-sm btn-danger" value="nonaktif">
                                        @else
                                        <input type="hidden" name="status" value="aktif">
                                        <input type="submit" class="btn btn-sm btn-success" value="aktif">
                                        @endif
                                    </form>

                                </td>
                            </tr>

                                                            
                        </tbody>
                    </table>
                    </div>
                </div>
            </div>
        </div>
    </div>                                        

@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('position.index') }}",
        columns: [
            { data: 'DT_RowIndex', orderable: false, searchable: false, className: "text-center"},
            { data: 'name' }
        ]
    })
</script>
@endpush

resources/views/editEmployee.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Pekerja</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
    </div>
    <div class="card-body">
      <form action="{{url('employee/'.$data->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        <input type="hidden" name="_method" value="PATCH">
        <div class="form-group">
          <label for="nama">Nama</label>
          <input type="text" class="form-control" id="nama" name="nama" value="{{$data->nama}}">
        </div>
        <div class="form-group">
          <label for="NIP">NIP</label>
          <input type="text" class="form-control" id="NIP" name="nip"  value="{{$data->nip}}">
        </div>
        <div class="form-group">
          <label for="Jabatan">Jabatan</label>
          <select class="form-control" id="Jabatan" name="jabatan">
            @foreach ($position as $p)
                @if($data->position_id==$p->id)
                    <option value="{{$p->id}}" selected>{{$p->name}}</option>
                @else
                    <option value="{{$p->id}}">{{$p->name}}</option>
                @endif
            @endforeach
          </select>
        </div>
        <div class="form-group">
          <label for="Departemen">Departemen</label>
          <input type="text" class="form-control" id="Departemen" name="departemen" value="{{$data->departemen}}">
        </div>
        <div class="form-group">
          <label for="Tanggal_Lahir">Tanggal Lahir</label>
          <input type="text" class="form-control" id="Tanggal_Lahir" name="tgl" value="{{$data->tanggal_lahir}}">
        </div>
        
        <div class="form-group">
          <label for="Alamat">Alamat</label>
          <input type="textarea" class="form-control" id="Alamat" name="alamat" value="{{$data->alamat}}">
        </div>
        <div class="form-group">
          <label for="Nohp">Nomor Telepon</label>
          <input type="number" class="form-control" id="Nohp" name="nohp" value="{{$data->nohp}}">
        </div>

        <div class="form-group">
          <label>Agama</label>
          <div class="custom-control custom-radio">
            <input type="radio" id="islam" name="agama" class="custom-control-input" value="islam" <?php if($data->agama=="islam"){echo "checked";}?>>
            <label class="custom-control-label" for="islam">Islam</label>
          </div>
          <div class="custom-control custom-radio">
            <input type="radio" id="Kristen" name="agama" class="custom-control-input" value="kristen" <?php if($data->agama=="kristen"){echo "checked";}?>>
            <label class="custom-control-label" for="Kristen">Kristen</label>
          </div>
          <div class="custom-control custom-radio">
            <input type="radio" id="Budha" name="agama" class="custom-control-input" value="budha" <?php if($data->agama=="budha"){echo "checked";}?>>
            <label class="custom-control-label" for="Budha">Budha</label>
          </div>
          <div class="custom-control custom-radio">
            <input type="radio" id="Hindu" name="agama" class="custom-control-input" value="hindu" <?php if($data->agama=="hindu"){echo "checked";}?>>
            <label class="custom-control-label" for="Hindu">Hindu</label>
          </div>
        </div>
        <div class="form-group">
          <label for="foto">File Foto KTP</label>
          <input type="file" class="form-control-file" id="foto" name="foto" placeholder="foto">
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>

      </form>
    </div>
</div>

@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
@endpush

resources/views/layout/footer.blade.php
<!-- Footer -->
<div class="row">
    <div class="col-lg-12 text-center">
      <p>Do you like this template ? you can download from <a href="https://github.com/indrijunanda/RuangAdmin"
          class="btn btn-primary btn-sm" target="_blank"><i class="fab fa-fw fa-github"></i>&nbsp;GitHub</a></p>
    </div>
  </div>
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
        <span>copyright &copy; <script> document.write(new Date().getFullYear()); </script> - developed by
            <b><a href="https://indrijunanda.gitlab.io/" target="_blank">indrijunanda</a></b>
        </span>
        </div>
    </div>
</footer>
<!-- Footer -->

resources/views/layout/sidebar.blade.php
<!-- Sidebar -->
<ul class="navbar-nav sidebar sidebar-light accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url('/') }}">
        <div class="sidebar-brand-icon">
        <img src="img/logo/logo3.png">
        </div>
        <div class="sidebar-brand-text mx-3"></div>
    </a>
    <hr class="sidebar-divider my-0">
    <li class="nav-item active">
        <a class="nav-link" href="{{ url('/') }}">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Fitur
    </div>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('position.index') }}">
            <i class="fas fa-sort-amount-up"></i>
        <span>Jabatan</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('employee.index') }}">
            <i class="fas fa-user"></i>
        <span>Karyawan</span>
        </a>
    </li>
    <hr class="sidebar-divider">
    <div class="version" id="version-ruangadmin"></div>
</ul>
<!-- Sidebar -->

resources/views/layout/topbar.blade.php
<!-- TopBar -->
<nav class="navbar navbar-expand navbar-light bg-navbar topbar mb-4 static-top">
    <button id="sidebarToggleTop" class="btn btn-link rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
</nav>
<!-- Topbar -->

resources/views/position.blade.php
@extends('layout.app')

@section('css')
  <link href="{{ asset('vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection
@section('breadcrumb')
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Jabatan</h1>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ url('/') }}">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Jabatan</li>
    </ol>
</div>
@endsection
@section('content')
<div class="card sm mb-4">
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary"></h6>
    </div>
    <div class="card-body">
        <div class="table-responsive p-3">
            <table class="table align-items-center table-flush" id="dataTable">
              <thead class="thead-light">
                <tr>
                  <th>No.</th>
                  <th>Name</th>
                </tr>
              </thead>
            </table>
          </div>
    </div>
</div>
@endsection

@push('js')
<script src="{{ asset('vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script>
    $('#dataTable').DataTable({
        processing: true,
        serverSide: true,
        ajax: "{{ route('position.index') }}",
        columns: [
            { data: 'DT_RowIndex', orderable: false, searchable: false, className: "text-center"},
            { data: 'name' }
        ]
    })
</script>
@endpush